name: CI/CD Database Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MySQL Connector
        run: pip install mysql-connector-python

      - name: Run SQL Script
        run: |
          python run_sql.py
