name: CI/CD for DB Deployment

on:
  push:
    branches:
      - test

jobs:
  db-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: devpwd123
          MYSQL_DATABASE: companydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Wait for MySQL to be ready
      run: sleep 30

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install mysql-connector-python

    - name: Run schema changes
      run: python execute_sql.py
